### ISSUE TITLE
Why there are other than Japanese languages translations?

### ISSUE THREAD

**Issue by dima74** [ArchLinuxJP/arch-package-description#1]
Could you say, please, why there is translations for, e.g., russian language? Afaik it is not used anywhere.

**Comment by kusakata** [comment]
Translations are used in the package page of Japanese Arch Linux website (https://www.archlinux.jp/packages/).
You can translate texts in Transifex (https://www.transifex.com/archlinuxjp/arch-package-description/) which will be imported into this website weekly.

But, it seemed that languages whose locale codes include an underscore (ex. ru_RU) didn't appear as expected.
Transifex uses the underscore instead of the hyphen for locale codes by default, but browsers send locale codes hyphen-separated (ex. ru-RU).

I commited necessary changes to Japanese website's code for languages including hyphen, so you could read Russian translated description in the website now.
Sorry for your inconvenience.

relevant commit: https://github.com/ArchLinuxJP/archweb-jp/commit/a2fd6374813c4d22463bb46986c9d6482a115967
