### ISSUE TITLE
Question about non-Japanese translations

### ISSUE THREAD

**Issue by dima74** [ArchLinuxJP/arch-package-description#2]
There are translations of packages description for many languages (for example, russian). Could you say, please, are there translations of interface titles (for example strings on main page https://www.archlinux.jp/). If no, maybe you will add them? If you don't want to add, could you say please, what is purpose of having translations of package descriptions and not having translations of all other strings. Thank you anyway.

Sorry about this issue (maybe it is not relative to this repository).

**Comment by kusakata** [comment]
> Could you say, please, are there translations of interface titles (for example strings on main page https://www.archlinux.jp/). 

Yes and no. There are interface strings on the package page (https://www.archlinux.jp/packages/). However there aren't interface strings on the other pages (including the main page).

> If no, maybe you will add them?

We have no intentions to add interface strings on pages other than the package page.

> If you don't want to add, could you say please, what is purpose of having translations of package descriptions and not having translations of all other strings.

First, the Japanese Arch Linux website is fundamentally for the Japanese. For Russians, there is the decent Arch Linux community's website by Russians (https://archlinux.org.ru/).
If I added the strings for the Japanese website's other pages, even one person (except for the Japanese) couldn't care of those.
He or she just can visit the community website written in his or her mother tongue.
You really want to translate the whole Japanese website into Russian, I guess I have to add the strings.

Second, I think the translations of package descriptions are useful for all non-native speakers of English.
It would be good if everyone could read the descriptions translated by their own languages similar to Debian Description Translation Project.
Moreover, because the nature of only having translations of package descriptions, translated texts might be used for various things.
Not only for the website, but also say the future pacman package wrapper (for outputting translated description) could download and use translations.

Thank you for submitting your questions 😃.
